# Generated by Django 3.1.5 on 2022-05-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=240, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=240, null=True)),
                ('pincode', models.CharField(max_length=240, null=True)),
                ('city', models.CharField(max_length=240, null=True)),
                ('district', models.CharField(max_length=240, null=True)),
                ('state', models.CharField(max_length=240, null=True)),
                ('country', models.CharField(max_length=240, null=True)),
                ('address1', models.CharField(max_length=240, null=True)),
                ('address2', models.CharField(max_length=240, null=True)),
                ('mobile', models.CharField(max_length=240, null=True)),
                ('aadharno', models.CharField(max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('password', models.CharField(max_length=240, null=True)),
                ('education', models.CharField(max_length=240, null=True)),
                ('experience', models.CharField(max_length=240, null=True)),
                ('skills', models.CharField(max_length=240, null=True)),
                ('idproof', models.FileField(blank=True, null=True, upload_to='images/')),
                ('addressproof', models.FileField(blank=True, null=True, upload_to='images/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('joiningdate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='', max_length=240, null=True)),
                ('worktype', models.CharField(default='', max_length=100, null=True)),
                ('cityandpin', models.CharField(default='', max_length=100, null=True)),
                ('costdayshrs', models.CharField(default='', max_length=100, null=True)),
                ('usertype', models.CharField(default='', max_length=100, null=True)),
                ('contracttype', models.CharField(default='', max_length=100, null=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userregistrationdesignation', to='job.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=240, null=True)),
                ('reporterid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Feedbackworkerid', to='job.user_registration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Feedbackuser', to='job.user_registration')),
            ],
        ),
    ]
