# Generated by Django 4.0.2 on 2022-05-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.CharField(default='', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(default='', max_length=240, null=True),
        ),
    ]
