# Generated by Django 4.0.2 on 2022-05-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='work',
        ),
    ]
