# Generated by Django 4.0.2 on 2022-05-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_user_registration_work_user_registration_work_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='work_id',
            new_name='worker_id',
        ),
    ]
