# Generated by Django 4.0.2 on 2022-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_work_id_user_registration_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='contractor_id',
            field=models.CharField(default='', max_length=240, null=True),
        ),
    ]
